using Microsoft.VisualStudio.Language.StandardClassification;
using Microsoft.VisualStudio.Text.Classification;
using Microsoft.VisualStudio.Utilities;
using System.ComponentModel.Composition;

namespace Color.Misc
{
	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.White")]
	[Name("Color.White")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_White
	:
		ClassificationFormatDefinition
	{
		public Format_White()
		{
			DisplayName = "_ Color: White";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.White;
		}
	}

	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.Silver")]
	[Name("Color.Silver")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_Silver
	:
		ClassificationFormatDefinition
	{
		public Format_Silver()
		{
			DisplayName = "_ Color: Silver";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.Silver;
		}
	}

	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.Gray")]
	[Name("Color.Gray")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_Gray
	:
		ClassificationFormatDefinition
	{
		public Format_Gray()
		{
			DisplayName = "_ Color: Gray";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.Gray;
		}
	}

	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.Dark")]
	[Name("Color.Dark")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_Dark
	:
		ClassificationFormatDefinition
	{
		public Format_Dark()
		{
			DisplayName = "_ Color: Dark";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.Dark;
		}
	}

	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.Black")]
	[Name("Color.Black")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_Black
	:
		ClassificationFormatDefinition
	{
		public Format_Black()
		{
			DisplayName = "_ Color: Black";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.Black;
		}
	}
	
	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.Red")]
	[Name("Color.Red")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_Red
	:
		ClassificationFormatDefinition
	{
		public Format_Red()
		{
			DisplayName = "_ Color: Red";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.Red;
		}
	}

	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.Orange")]
	[Name("Color.Orange")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_Orange
	:
		ClassificationFormatDefinition
	{
		public Format_Orange()
		{
			DisplayName = "_ Color: Orange";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.Orange;
		}
	}

	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.Yellow")]
	[Name("Color.Yellow")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_Yellow
	:
		ClassificationFormatDefinition
	{
		public Format_Yellow()
		{
			DisplayName = "_ Color: Yellow";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.Yellow;
		}
	}

	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.Lime")]
	[Name("Color.Lime")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_Lime
	:
		ClassificationFormatDefinition
	{
		public Format_Lime()
		{
			DisplayName = "_ Color: Lime";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.Lime;
		}
	}

	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.Green")]
	[Name("Color.Green")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_Green
	:
		ClassificationFormatDefinition
	{
		public Format_Green()
		{
			DisplayName = "_ Color: Green";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.Green;
		}
	}

	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.Turquoise")]
	[Name("Color.Turquoise")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_Turquoise
	:
		ClassificationFormatDefinition
	{
		public Format_Turquoise()
		{
			DisplayName = "_ Color: Turquoise";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.Turquoise;
		}
	}

	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.Cyan")]
	[Name("Color.Cyan")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_Cyan
	:
		ClassificationFormatDefinition
	{
		public Format_Cyan()
		{
			DisplayName = "_ Color: Cyan";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.Cyan;
		}
	}

	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.Blue")]
	[Name("Color.Blue")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_Blue
	:
		ClassificationFormatDefinition
	{
		public Format_Blue()
		{
			DisplayName = "_ Color: Blue";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.Blue;
		}
	}

	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.Violet")]
	[Name("Color.Violet")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_Violet
	:
		ClassificationFormatDefinition
	{
		public Format_Violet()
		{
			DisplayName = "_ Color: Violet";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.Violet;
		}
	}

	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.Purple")]
	[Name("Color.Purple")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_Purple
	:
		ClassificationFormatDefinition
	{
		public Format_Purple()
		{
			DisplayName = "_ Color: Purple";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.Purple;
		}
	}

	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.Magenta")]
	[Name("Color.Magenta")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_Magenta
	:
		ClassificationFormatDefinition
	{
		public Format_Magenta()
		{
			DisplayName = "_ Color: Magenta";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.Magenta;
		}
	}

	[Export(typeof(EditorFormatDefinition))]
	[ClassificationType(ClassificationTypeNames = "Color.Rose")]
	[Name("Color.Rose")]
	[BaseDefinition(PredefinedClassificationTypeNames.Identifier)]
	[UserVisible(true)]
	[Order(After = Priority.High)]
	[Order(After = PredefinedClassificationTypeNames.Character)]
	[Order(After = PredefinedClassificationTypeNames.Comment)]
	[Order(After = PredefinedClassificationTypeNames.ExcludedCode)]
	[Order(After = PredefinedClassificationTypeNames.FormalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Identifier)]
	[Order(After = PredefinedClassificationTypeNames.Keyword)]
	[Order(After = PredefinedClassificationTypeNames.Literal)]
	[Order(After = PredefinedClassificationTypeNames.NaturalLanguage)]
	[Order(After = PredefinedClassificationTypeNames.Number)]
	[Order(After = PredefinedClassificationTypeNames.Operator)]
	[Order(After = PredefinedClassificationTypeNames.Other)]
	[Order(After = PredefinedClassificationTypeNames.PreprocessorKeyword)]
	[Order(After = PredefinedClassificationTypeNames.String)]
	[Order(After = PredefinedClassificationTypeNames.SymbolDefinition)]
	[Order(After = PredefinedClassificationTypeNames.SymbolReference)]
	[Order(After = PredefinedClassificationTypeNames.Type)]
	[Order(After = PredefinedClassificationTypeNames.WhiteSpace)]
	[Order(After = "(TRANSIENT)")]
	[Order(After = "text")]
	[Order(After = "sighelp-documentation")]
	[Order(After = "currentParam")]
	[Order(After = "XML Doc Comment")]
	[Order(After = "XML Doc Tag")]
	[Order(After = "C/C++ User Keywords")]
	[Order(After = "CppInactiveCodeClassification")]
	[Order(After = "CppSolidColorClassification")]
	[Order(After = "cppMacro")]
	[Order(After = "cppEnumerator")]
	[Order(After = "cppGlobalVariable")]
	[Order(After = "cppLocalVariable")]
	[Order(After = "cppParameter")]
	[Order(After = "cppType")]
	[Order(After = "cppRefType")]
	[Order(After = "cppValueType")]
	[Order(After = "cppFunction")]
	[Order(After = "cppMemberFunction")]
	[Order(After = "cppMemberField")]
	[Order(After = "cppStaticMemberFunction")]
	[Order(After = "cppStaticMemberField")]
	[Order(After = "cppProperty")]
	[Order(After = "cppEvent")]
	[Order(After = "cppClassTemplate")]
	[Order(After = "cppGenericType")]
	[Order(After = "cppFunctionTemplate")]
	[Order(After = "cppNamespace")]
	[Order(After = "cppLabel")]
	[Order(After = "cppStringDelimiterCharacter")]
	[Order(After = "cppControlKeyword")]
	internal sealed class Format_Rose
	:
		ClassificationFormatDefinition
	{
		public Format_Rose()
		{
			DisplayName = "_ Color: Rose";

			BackgroundCustomizable = false;
			ForegroundColor = Default.Colors.Rose;
		}
	}
}